/datum/map/away_sites_testing
	// Unit test exemptions
	apc_test_exempt_areas = list(
		/area/AIsattele = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/constructionsite = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/constructionsite/ai = NO_SCRUBBER|NO_VENT,
		/area/constructionsite/atmospherics = NO_SCRUBBER,
		/area/constructionsite/teleporter = NO_SCRUBBER,
		/area/derelict/ship = NO_SCRUBBER|NO_VENT,
		/area/djstation = NO_SCRUBBER|NO_APC,
		/area/mine/explored = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/mine/unexplored = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/outpost/abandoned = NO_SCRUBBER,
		/area/space = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/ship/scrap/maintenance/engine/port = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/maintenance/engine/starboard = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/crew/hallway/port= NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/crew/hallway/starboard= NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/maintenance/hallway = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/maintenance/lower = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/maintenance/atmos = NO_SCRUBBER,
		/area/ship/scrap/escape_port = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/escape_star = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/shuttle/lift = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/ship/scrap/damselfly = NO_SCRUBBER|NO_VENT,
		/area/ship/scrap/command/hallway = NO_SCRUBBER|NO_VENT,
		/area/lost_supply_base/solar = NO_SCRUBBER,
		/area/slavers_base/hangar = NO_SCRUBBER,
		/area/map_template/hydrobase = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/map_template/hydrobase/station = NO_SCRUBBER,
		/area/map_template/marooned = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/jungleoutpost/medbay = NO_SCRUBBER|NO_VENT,
		/area/jungleoutpost/comms = NO_SCRUBBER,
		/area/planet/jungle/away = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/planet/destroyed_colony = NO_SCRUBBER|NO_VENT|NO_APC,

		/area/noctis/exteriorl = NO_SCRUBBER|NO_VENT,
		/area/noctis/apm = NO_SCRUBBER|NO_VENT,
		/area/noctis/disposal = NO_SCRUBBER|NO_VENT,
		/area/noctis/reactorch = NO_SCRUBBER|NO_VENT,
		/area/noctis/raptor = NO_SCRUBBER,
		/area/noctis/fm = NO_SCRUBBER|NO_VENT,
		/area/noctis/combint = NO_SCRUBBER|NO_VENT,
		/area/noctis/atmosc = NO_SCRUBBER|NO_VENT,
		/area/noctis/atmos = NO_SCRUBBER|NO_VENT,
		/area/noctis/reactorov = NO_SCRUBBER|NO_VENT,
		/area/noctis/extconn = NO_SCRUBBER|NO_VENT,
		/area/noctis/fpm = NO_SCRUBBER|NO_VENT,
	)

	area_coherency_test_exempt_areas = list(
		/area/space,
		/area/mine/explored,
		/area/mine/unexplored,
	)

	area_coherency_test_subarea_count = list(
		/area/constructionsite = 7,
		/area/constructionsite/maintenance = 14,
		/area/constructionsite/solar = 3,
	)

	area_usage_test_exempted_areas = list(
		/area/overmap,
		/area/template_noop,
		/area/centcom,
		/area/centcom/holding,
		/area/centcom/specops,
		/area/chapel,
		/area/hallway,
		/area/medical,
		/area/medical/virology,
		/area/medical/virologyaccess,
		/area/medical/virology,
		/area/security,
		/area/security/brig,
		/area/security/prison,
		/area/maintenance,
		/area/rnd,
		/area/rnd/xenobiology,
		/area/rnd/xenobiology/xenoflora,
		/area/rnd/xenobiology/xenoflora_storage,
		/area/shuttle,
		/area/shuttle/escape,
		/area/shuttle/escape/centcom,
		/area/shuttle/specops,
		/area/shuttle/specops/centcom,
		/area/shuttle/syndicate_elite,
		/area/shuttle/syndicate_elite/mothership,
		/area/shuttle/syndicate_elite/station,
		/area/skipjack_station,
		/area/skipjack_station/start,
		/area/supply,
		/area/syndicate_mothership,
		/area/syndicate_mothership/elite_squad,
		/area/turbolift,
		/area/map_template/hydrobase
	)

	area_usage_test_exempted_root_areas = list(
		/area/exoplanet,
		/area/map_template,
	)
