version: "3.3"
services:
  db:
    build: ./sql
    image: ah13-db:latest
    networks:
      - internal
    volumes:
      - ".sql/test-db:/var/lib/mysql"
    restart: unless-stopped
  game:
    build: .
    image: ah13:latest
    networks:
      - internal
    volumes:
      - type: volume
        source: ./config
        target: /home/ah13-srv-usr/config
      - type: volume
        source: ./data
        target: /home/ah13-srv-usr/data
    ports:
      - "8000:8000"
networks:
  internal:
