[language_basic_common]
name = "Santiago Basic"
short_hand = "GC"
description = "The common galactic tongue."
syllables = [
	"blah","blah","blah","bleh","meh","neh","nah","wah"
]
key = "0"

[language_spacer]
name = "Spacer Croele"
short_hand = "SP"
description = """
	A pidgin language spoken by haulers, merchants, traders, travellers, and cocky fly-boys across the galaxy.
	"""
syllables = [
	"die", "en", "skei", "van", "son", "der", "aar", "ch", "op", "ruk", "aa", "be", "ne", "het",
	"ek", "ras", "ver", "zan", "das", "waa", "geb", "vol", "lu", "min", "breh", "rus", "stv",
	"ee", "goe", "sk","la", "ver", "we", "ge", "luk", "an", "ar", "at", "es", "et", "bel", "du",
	"jaa", "ch", "kk", "gh", "ll", "uu", "wat"
]
colour = "spacer"
key = "e"
