#define RECHARGING 0x1
#define CHARGED 0x2
#define FIRING 0x4
#define NO_AMMO 0x8

#define COMBAT_CHANNEL_PUBLIC "public"
#define COMBAT_CHANNEL_PRIVATE "private"
#define COMBAT_CHANNEL_TECHNICAL "technical"

#define ALL_COMBAT_CHANNELS \
list(COMBAT_CHANNEL_PUBLIC,COMBAT_CHANNEL_PRIVATE,COMBAT_CHANNEL_TECHNICAL)
