[cultures_common]
language = "language_spacer"
secondary_languages = ["language_sol_common", "language_sign", "language_basic_common"]

[cultures_common_spacer]
__extends = 'cultures_common'
name = "Spacer"
description = """Unbound to planets, societies, or nationalities. It’s the
	space that is your home, the space is infinite, and it is not empty as most
	people make it to be. The long arm of law and justice is short here, for
	better and ill. It doesn’t matter who you are, you can be anything, the void
	doesn’t care."""

[cultures_common_rimmer]
__extends = 'cultures_common'
name = "Rimmer"
description = """For a reason or other, destiny has entrusted you into a fate
	or childhood on a world at fringes of civilization known to man. Either you’ve
	been part of the colonial boom, or you’d been born into a former colony declined
	into tribalism. You’ve been bestowed the honour escaping this life thanks to a
	bypassing ship, or managed to find an old still-working ship, bringing you back
	to the stars."""

[cultures_common_other]
__extends = 'cultures_common'
name = "Other"
