[culture_vox]
language = "language_vox_basic"
secondary_langs = ["language_spacer_basic"]
category = ["culture"]

[culture_vox_old]
__extends = 'culture_vox'
name = "Arker"
description = """Arkships are generation ships with hundreds thousands
	cryosleepers to keep the crew and sleepers in comfort and stasis against
	the wear of aging and the elements of the cold void. The reason how and why
	the Arkships exist are thought to be an constant escape from an ancient
	threat that destroyed the old Vox homes; the Galactic Crisis. Every now and
	then a fraction of the sleepers are revived to conduct maintenance and
	collect resources to keep the Arkships running."""

[culture_vox_settler]
__extends = 'culture_vox'
name = "Settler"
scription = """Arkships are for those who believe in running away from a
	threat, there has been kind like the colonists before, but no one has heard
	of them again. Instead of sticking to the Arkship life, Vox has settled down
	for a calm and peaceful life, cursing the old ways and embracing a change of
	air for new life. This time it is different, never once in hundred cycles
	have the Vox met an actual civilized sector like this. A new future for the
	Vox, perhaps!"""

[culture_vox_new]
__extends = 'culture_vox'
name = "Neoedener"
description = """The sheltered life stuck to the old Apex and the Arkships have
	caused a great stagnation and massive loss of knowledge, the kin sick with
	dependency on old flawing technology to stay alive. Thanks to cowardice the
	old homeworlds are destroyed and far far away. Enough is enough, it’s time to
	for once settle down on a world and rebuild a world like the old home as how
	the Vox can remember it, and regain the Vox their own identity."""
