[culture_teshari]
language = "language_teshari_basic"
secondary_langs = ["language_skrell_basic", "language_spacer"]

[culture_teshari_qerr]
__extends = 'culture_teshari'
name = "Qerr'tesh"
description = """Qerr’Teshari is a namesake invented by the Qerr’Balakan
Skrell, the Teshari homeworld was conveniently few rocks away from the
Skrellian homeworld. The Teshari were at a lower technological advantage
when discovered by Skrell. Since then, the Qerr’Balakans have imposed a
protectorate government on the Teshari, adopting them to the Technocracy.
The Qerr’Teshari are considered an example of having low culture and high
technology, not yet acclimated to new powers of technology."""

[culture_teshari_sceechi]
__extends = 'culture_teshari'
name = "Sceechi"
description = """Sceechi are an acceleration of Qerr’Teshari culture and
often deviate from norms and ideas ingrained or educated by Qerr’Balakans.
This family of cultures are rapid adoptions to the new technology, thus they
are seen as an young generation of subcultures. Exposure to the technology
and its benefits also had led to a simplified pidgin of the Teshari language
and Skrellian tongues. Unpopular with the more sophisticated ranks of
Qerr’Balakans for being deviate and young."""
