name: Changelog Automaker (Generate PR CL)

on:
  push:
    branches: [master]

env:
  GIT_EMAIL: "action@github.com"
  GIT_NAME: "Changelog Automaker"
  CL_AUTOMAKER_DIR: "./tools/ChangelogAutomaker"

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    # discriminator to exclude forks
    if: github.repository == 'Haven-13/Haven-Urist'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub pyyaml bs4
      - name: Generate CL
        run: python $CL_AUTOMAKER_DIR/generate_cl.py
      - name: Commit
        run: |
          git config --local user.email $GIT_EMAIL
          git config --local user.name "$GIT_NAME"
          git pull origin master
          git commit -m "Auto-CL generate [ci skip]" -a || true
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
