name: PR Check
on:
  pull_request:
    branches:
    - latest
jobs:
  lint_cl:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Tools
        run: |
          pip3 install setuptools
          tools/bootstrap/python -c ''
      - name: Check changelog
        run: bash tools/ci/check_changelogs.sh
